version: '2'
services:
  bumblebee:
    build: ./
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - TZ=Asia/Singapore
  redis:
    image: redis
